### ISSUE TITLE
Error When You Click Launch - KeyError: library/animations

### ISSUE THREAD

**Issue by smaitlx** [Spacehaven-modding-tools/spacehaven-modloader#26]
The following error is presented:

Traceback (most recent call last):
    File "spacehaven-modloader.py", line 641, in patchAndLaunch
    File "loader\load.py", line 32, in load
    File "loader\assets\merge.py", line 280, in mods
KeyError: 'library/animations'

**Comment by smaitlx** [comment]
I've been able to resolve this.  In one of the mods, there was a textures folder.  The mod does not use any textures, so I deleted that folder and everything worked as expected.
